import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { registerSW } from 'virtual:pwa-register';
import './index.css';
import App from './App.tsx';
import { storageService } from './services/StorageService.ts';
import type { CatEncounter } from './types/index.ts';

// Register the service worker generated by vite-plugin-pwa
if ('serviceWorker' in navigator) {
  registerSW({ immediate: true });
}

const addTestEncounters = async () => {
  const testEncounters: CatEncounter[] = [
    {
      id: 'test-1',
      catColor: 'black',
      coatLength: 'short',
      catType: 'domestic short-hair',
      dateTime: new Date().toISOString(),
      lat: 40.7128,
      lng: -74.0060, // NYC
      behavior: 'friendly',
      comment: 'Test black cat encounter.',
      photoBlobId: undefined,
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
    {
      id: 'test-2',
      catColor: 'white',
      coatLength: 'short',
      catType: 'domestic long-hair',
      dateTime: new Date().toISOString(),
      lat: 34.0522,
      lng: -118.2437, // Los Angeles
      behavior: 'shy',
      comment: 'Test white cat encounter.',
      photoBlobId: undefined,
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
    {
      id: 'test-3',
      catColor: 'orange',
      coatLength: 'short',
      catType: 'tabby',
      dateTime: new Date().toISOString(),
      lat: 51.5074,
      lng: -0.1278, // London
      behavior: 'playful',
      comment: 'Test orange cat encounter.',
      photoBlobId: undefined,
      updatedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
    },
  ];

  for (const encounter of testEncounters) {
    await storageService.saveEncounter(encounter);
  }
  const currentEncounters = await storageService.getEncounters();
  console.log('Main.tsx: Added test encounters. Current encounters in DB:', JSON.stringify(currentEncounters, null, 2));
};

async function initializeApp() {
  await addTestEncounters();

  createRoot(document.getElementById('root')!).render(
    <StrictMode>
      <App />
    </StrictMode>,
  )
}

initializeApp();
