import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { createBrowserRouter, RouterProvider } from 'react-router-dom';
import { registerSW } from 'virtual:pwa-register';
import './index.css';
import App from './App.tsx';
import { PrivacyPolicy } from './pages/PrivacyPolicy.tsx';
import { TermsOfService } from './pages/TermsOfService.tsx';

// Register the service worker generated by vite-plugin-pwa
if ('serviceWorker' in navigator) {
  registerSW({ immediate: true });
}

const router = createBrowserRouter([
  {
    path: '/',
    element: <App />,
  },
  {
    path: '/policy',
    element: <PrivacyPolicy />,
  },
  {
    path: '/tos',
    element: <TermsOfService />,
  },
]);

async function initializeApp() {
  createRoot(document.getElementById('root')!).render(
    <StrictMode>
      <RouterProvider router={router} />
    </StrictMode>,
  )
}

initializeApp();
